/* tslint:disable */
/* eslint-disable */
/**
 * Pieces Isomorphic OpenAPI
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from "../runtime.ts";
import type { Activity } from "./Activity.tsx";
import { ActivityFromJSON, ActivityToJSON } from "./Activity.tsx";
import type { EmbeddedModelSchema } from "./EmbeddedModelSchema.tsx";
import {
	EmbeddedModelSchemaFromJSON,
	EmbeddedModelSchemaToJSON,
} from "./EmbeddedModelSchema.tsx";

/**
 * This is the plural of activity
 * @export
 * @interface Activities
 */
export interface Activities {
	/**
	 *
	 * @type {EmbeddedModelSchema}
	 * @memberof Activities
	 */
	schema?: EmbeddedModelSchema;
	/**
	 *
	 * @type {Array<Activity>}
	 * @memberof Activities
	 */
	iterable: Activity[];
}

/**
 * Check if a given object implements the Activities interface.
 */
export function instanceOfActivities(value: object): boolean {
	let isInstance = true;
	isInstance = isInstance && "iterable" in value;

	return isInstance;
}

export function ActivitiesFromJSON(json: any): Activities {
	return ActivitiesFromJSONTyped(json, false);
}

export function ActivitiesFromJSONTyped(
	json: any,
	_ignoreDiscriminator: boolean,
): Activities {
	if (json === undefined || json === null) {
		return json;
	}
	return {
		schema: exists(json, "schema")
			? EmbeddedModelSchemaFromJSON(json["schema"])
			: undefined,
		iterable: (json["iterable"] as any[]).map(ActivityFromJSON),
	};
}

export function ActivitiesToJSON(value?: Activities | null): any {
	if (value === undefined) {
		return undefined;
	}
	if (value === null) {
		return null;
	}
	return {
		schema: EmbeddedModelSchemaToJSON(value.schema),
		iterable: (value.iterable as any[]).map(ActivityToJSON),
	};
}
