/* tslint:disable */
/* eslint-disable */
/**
 * Pieces Isomorphic OpenAPI
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from "../runtime.ts";
import {
	EmbeddedModelSchemaFromJSON,
	EmbeddedModelSchemaToJSON,
	type EmbeddedModelSchema,
} from "./EmbeddedModelSchema.tsx";
import {
	GroupedTimestampFromJSON,
	GroupedTimestampToJSON,
	type GroupedTimestamp,
} from "./GroupedTimestamp.tsx";

/**
 * if you want a range between you can use from && to.
 *
 * if you want anything before, use to and NO from.
 *
 * if you want anything after, use from and NO to.
 * @export
 * @interface AssetFilterTimestamp
 */
export interface AssetFilterTimestamp {
	/**
	 *
	 * @type {EmbeddedModelSchema}
	 * @memberof AssetFilterTimestamp
	 */
	schema?: EmbeddedModelSchema;
	/**
	 *
	 * @type {GroupedTimestamp}
	 * @memberof AssetFilterTimestamp
	 */
	from?: GroupedTimestamp;
	/**
	 *
	 * @type {GroupedTimestamp}
	 * @memberof AssetFilterTimestamp
	 */
	to?: GroupedTimestamp;
	/**
	 *
	 * @type {boolean}
	 * @memberof AssetFilterTimestamp
	 */
	between?: boolean;
}

/**
 * Check if a given object implements the AssetFilterTimestamp interface.
 */
export function instanceOfAssetFilterTimestamp(_value: object): boolean {
	const isInstance = true;

	return isInstance;
}

export function AssetFilterTimestampFromJSON(json: any): AssetFilterTimestamp {
	return AssetFilterTimestampFromJSONTyped(json, false);
}

export function AssetFilterTimestampFromJSONTyped(
	json: any,
	_ignoreDiscriminator: boolean,
): AssetFilterTimestamp {
	if (json === undefined || json === null) {
		return json;
	}
	return {
		schema: exists(json, "schema")
			? EmbeddedModelSchemaFromJSON(json["schema"])
			: undefined,
		from: exists(json, "from")
			? GroupedTimestampFromJSON(json["from"])
			: undefined,
		to: exists(json, "to")
			? GroupedTimestampFromJSON(json["to"])
			: undefined,
		between: exists(json, "between") ? json["between"] : undefined,
	};
}

export function AssetFilterTimestampToJSON(
	value?: AssetFilterTimestamp | null,
): any {
	if (value === undefined) {
		return undefined;
	}
	if (value === null) {
		return null;
	}
	return {
		schema: EmbeddedModelSchemaToJSON(value.schema),
		from: GroupedTimestampToJSON(value.from),
		to: GroupedTimestampToJSON(value.to),
		between: value.between,
	};
}
