/* tslint:disable */
/* eslint-disable */
/**
 * Pieces Isomorphic OpenAPI
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from "../runtime.ts";
import { AssetFromJSON, AssetToJSON, type Asset } from "./Asset.tsx";
import {
	EmbeddedModelSchemaFromJSON,
	EmbeddedModelSchemaToJSON,
	type EmbeddedModelSchema,
} from "./EmbeddedModelSchema.tsx";
import { ScoreFromJSON, ScoreToJSON, type Score } from "./Score.tsx";

/**
 * A base class for a collection of assets and some additional meta properties. Fully Populated with Formats internally (not just uuid's).
 * @export
 * @interface Assets
 */
export interface Assets {
	/**
	 *
	 * @type {EmbeddedModelSchema}
	 * @memberof Assets
	 */
	schema?: EmbeddedModelSchema;
	/**
	 *
	 * @type {Array<Asset>}
	 * @memberof Assets
	 */
	iterable: Asset[];
	/**
	 * This is a Map<String, int> where the the key is an asset id.
	 * @type {{ [key: string]: number; }}
	 * @memberof Assets
	 */
	indices?: { [key: string]: number };
	/**
	 *
	 * @type {Score}
	 * @memberof Assets
	 */
	score?: Score;
}

/**
 * Check if a given object implements the Assets interface.
 */
export function instanceOfAssets(value: object): boolean {
	let isInstance = true;
	isInstance = isInstance && "iterable" in value;

	return isInstance;
}

export function AssetsFromJSON(json: any): Assets {
	return AssetsFromJSONTyped(json, false);
}

export function AssetsFromJSONTyped(
	json: any,
	_ignoreDiscriminator: boolean,
): Assets {
	if (json === undefined || json === null) {
		return json;
	}
	return {
		schema: exists(json, "schema")
			? EmbeddedModelSchemaFromJSON(json["schema"])
			: undefined,
		iterable: (json["iterable"] as any[]).map(AssetFromJSON),
		indices: exists(json, "indices") ? json["indices"] : undefined,
		score: exists(json, "score") ? ScoreFromJSON(json["score"]) : undefined,
	};
}

export function AssetsToJSON(value?: Assets | null): any {
	if (value === undefined) {
		return undefined;
	}
	if (value === null) {
		return null;
	}
	return {
		schema: EmbeddedModelSchemaToJSON(value.schema),
		iterable: (value.iterable as any[]).map(AssetToJSON),
		indices: value.indices,
		score: ScoreToJSON(value.score),
	};
}
