/* tslint:disable */
/* eslint-disable */
/**
 * Pieces Isomorphic OpenAPI
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from "../runtime.ts";
import type { BrowserTabValue } from "./BrowserTabValue.tsx";
import {
	BrowserTabValueFromJSON,
	BrowserTabValueToJSON,
} from "./BrowserTabValue.tsx";
import type { EmbeddedModelSchema } from "./EmbeddedModelSchema.tsx";
import {
	EmbeddedModelSchemaFromJSON,
	EmbeddedModelSchemaToJSON,
} from "./EmbeddedModelSchema.tsx";

/**
 * Plural model that represent many tabs
 * @export
 * @interface BrowserTabValues
 */
export interface BrowserTabValues {
	/**
	 *
	 * @type {EmbeddedModelSchema}
	 * @memberof BrowserTabValues
	 */
	schema?: EmbeddedModelSchema;
	/**
	 *
	 * @type {Array<BrowserTabValue>}
	 * @memberof BrowserTabValues
	 */
	iterable: BrowserTabValue[];
}

/**
 * Check if a given object implements the BrowserTabValues interface.
 */
export function instanceOfBrowserTabValues(value: object): boolean {
	let isInstance = true;
	isInstance = isInstance && "iterable" in value;

	return isInstance;
}

export function BrowserTabValuesFromJSON(json: any): BrowserTabValues {
	return BrowserTabValuesFromJSONTyped(json, false);
}

export function BrowserTabValuesFromJSONTyped(
	json: any,
	_ignoreDiscriminator: boolean,
): BrowserTabValues {
	if (json === undefined || json === null) {
		return json;
	}
	return {
		schema: exists(json, "schema")
			? EmbeddedModelSchemaFromJSON(json["schema"])
			: undefined,
		iterable: (json["iterable"] as any[]).map(BrowserTabValueFromJSON),
	};
}

export function BrowserTabValuesToJSON(value?: BrowserTabValues | null): any {
	if (value === undefined) {
		return undefined;
	}
	if (value === null) {
		return null;
	}
	return {
		schema: EmbeddedModelSchemaToJSON(value.schema),
		iterable: (value.iterable as any[]).map(BrowserTabValueToJSON),
	};
}
