/* tslint:disable */
/* eslint-disable */
/**
 * Pieces Isomorphic OpenAPI
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from "../runtime.ts";
import {
	EmbeddedModelSchemaFromJSON,
	EmbeddedModelSchemaToJSON,
	type EmbeddedModelSchema,
} from "./EmbeddedModelSchema.tsx";
import {
	ExternalProviderFromJSON,
	ExternalProviderToJSON,
	type ExternalProvider,
} from "./ExternalProvider.tsx";

/**
 *
 * @export
 * @interface ExternalProviders
 */
export interface ExternalProviders {
	/**
	 *
	 * @type {EmbeddedModelSchema}
	 * @memberof ExternalProviders
	 */
	schema?: EmbeddedModelSchema;
	/**
	 *
	 * @type {Array<ExternalProvider>}
	 * @memberof ExternalProviders
	 */
	iterable: ExternalProvider[];
}

/**
 * Check if a given object implements the ExternalProviders interface.
 */
export function instanceOfExternalProviders(value: object): boolean {
	let isInstance = true;
	isInstance = isInstance && "iterable" in value;

	return isInstance;
}

export function ExternalProvidersFromJSON(json: any): ExternalProviders {
	return ExternalProvidersFromJSONTyped(json, false);
}

export function ExternalProvidersFromJSONTyped(
	json: any,
	_ignoreDiscriminator: boolean,
): ExternalProviders {
	if (json === undefined || json === null) {
		return json;
	}
	return {
		schema: exists(json, "schema")
			? EmbeddedModelSchemaFromJSON(json["schema"])
			: undefined,
		iterable: (json["iterable"] as any[]).map(ExternalProviderFromJSON),
	};
}

export function ExternalProvidersToJSON(value?: ExternalProviders | null): any {
	if (value === undefined) {
		return undefined;
	}
	if (value === null) {
		return null;
	}
	return {
		schema: EmbeddedModelSchemaToJSON(value.schema),
		iterable: (value.iterable as any[]).map(ExternalProviderToJSON),
	};
}
