/* tslint:disable */
/* eslint-disable */
/**
 * Pieces Isomorphic OpenAPI
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from "../runtime.ts";
import type { EmbeddedModelSchema } from "./EmbeddedModelSchema.tsx";
import {
	EmbeddedModelSchemaFromJSON,
	EmbeddedModelSchemaToJSON,
} from "./EmbeddedModelSchema.tsx";
import type { FlattenedShare } from "./FlattenedShare.tsx";
import {
	FlattenedShareFromJSON,
	FlattenedShareToJSON,
} from "./FlattenedShare.tsx";
import type { Score } from "./Score.tsx";
import { ScoreFromJSON, ScoreToJSON } from "./Score.tsx";

/**
 * This is just an iterable of our individual share models.
 * @export
 * @interface FlattenedShares
 */
export interface FlattenedShares {
	/**
	 *
	 * @type {EmbeddedModelSchema}
	 * @memberof FlattenedShares
	 */
	schema?: EmbeddedModelSchema;
	/**
	 *
	 * @type {Array<FlattenedShare>}
	 * @memberof FlattenedShares
	 */
	iterable: FlattenedShare[];
	/**
	 *
	 * @type {Score}
	 * @memberof FlattenedShares
	 */
	score?: Score;
}

/**
 * Check if a given object implements the FlattenedShares interface.
 */
export function instanceOfFlattenedShares(value: object): boolean {
	let isInstance = true;
	isInstance = isInstance && "iterable" in value;

	return isInstance;
}

export function FlattenedSharesFromJSON(json: any): FlattenedShares {
	return FlattenedSharesFromJSONTyped(json, false);
}

export function FlattenedSharesFromJSONTyped(
	json: any,
	_ignoreDiscriminator: boolean,
): FlattenedShares {
	if (json === undefined || json === null) {
		return json;
	}
	return {
		schema: exists(json, "schema")
			? EmbeddedModelSchemaFromJSON(json["schema"])
			: undefined,
		iterable: (json["iterable"] as any[]).map(FlattenedShareFromJSON),
		score: exists(json, "score") ? ScoreFromJSON(json["score"]) : undefined,
	};
}

export function FlattenedSharesToJSON(value?: FlattenedShares | null): any {
	if (value === undefined) {
		return undefined;
	}
	if (value === null) {
		return null;
	}
	return {
		schema: EmbeddedModelSchemaToJSON(value.schema),
		iterable: (value.iterable as any[]).map(FlattenedShareToJSON),
		score: ScoreToJSON(value.score),
	};
}
