/* tslint:disable */
/* eslint-disable */
/**
 * Pieces Isomorphic OpenAPI
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from "../runtime.ts";
import {
	ApplicationsFromJSON,
	ApplicationsToJSON,
	type Applications,
} from "./Applications.tsx";
import {
	EmbeddedModelSchemaFromJSON,
	EmbeddedModelSchemaToJSON,
	type EmbeddedModelSchema,
} from "./EmbeddedModelSchema.tsx";
import {
	FlattenedAnchorsFromJSON,
	FlattenedAnchorsToJSON,
	type FlattenedAnchors,
} from "./FlattenedAnchors.tsx";
import {
	FlattenedAnnotationsFromJSON,
	FlattenedAnnotationsToJSON,
	type FlattenedAnnotations,
} from "./FlattenedAnnotations.tsx";
import {
	FlattenedAssetsFromJSON,
	FlattenedAssetsToJSON,
	type FlattenedAssets,
} from "./FlattenedAssets.tsx";
import {
	FlattenedConversationsFromJSON,
	FlattenedConversationsToJSON,
	type FlattenedConversations,
} from "./FlattenedConversations.tsx";
import {
	FlattenedPersonsFromJSON,
	FlattenedPersonsToJSON,
	type FlattenedPersons,
} from "./FlattenedPersons.tsx";
import {
	FlattenedRangesFromJSON,
	FlattenedRangesToJSON,
	type FlattenedRanges,
} from "./FlattenedRanges.tsx";
import {
	FlattenedWebsitesFromJSON,
	FlattenedWebsitesToJSON,
	type FlattenedWebsites,
} from "./FlattenedWebsites.tsx";
import {
	FlattenedWorkstreamEventsFromJSON,
	FlattenedWorkstreamEventsToJSON,
	type FlattenedWorkstreamEvents,
} from "./FlattenedWorkstreamEvents.tsx";
import {
	GroupedTimestampFromJSON,
	GroupedTimestampToJSON,
	type GroupedTimestamp,
} from "./GroupedTimestamp.tsx";
import { ModelFromJSON, ModelToJSON, type Model } from "./Model.tsx";
import { ScoreFromJSON, ScoreToJSON, type Score } from "./Score.tsx";

/**
 * This is a DAG-Safe minimal representation of a workstream summary
 * @export
 * @interface FlattenedWorkstreamSummary
 */
export interface FlattenedWorkstreamSummary {
	/**
	 *
	 * @type {EmbeddedModelSchema}
	 * @memberof FlattenedWorkstreamSummary
	 */
	schema?: EmbeddedModelSchema;
	/**
	 *
	 * @type {string}
	 * @memberof FlattenedWorkstreamSummary
	 */
	id: string;
	/**
	 *
	 * @type {Score}
	 * @memberof FlattenedWorkstreamSummary
	 */
	score?: Score;
	/**
	 *
	 * @type {GroupedTimestamp}
	 * @memberof FlattenedWorkstreamSummary
	 */
	created: GroupedTimestamp;
	/**
	 *
	 * @type {GroupedTimestamp}
	 * @memberof FlattenedWorkstreamSummary
	 */
	updated: GroupedTimestamp;
	/**
	 *
	 * @type {FlattenedWorkstreamEvents}
	 * @memberof FlattenedWorkstreamSummary
	 */
	events?: FlattenedWorkstreamEvents;
	/**
	 *
	 * @type {string}
	 * @memberof FlattenedWorkstreamSummary
	 */
	name: string;
	/**
	 *
	 * @type {FlattenedAnnotations}
	 * @memberof FlattenedWorkstreamSummary
	 */
	annotations?: FlattenedAnnotations;
	/**
	 *
	 * @type {FlattenedRanges}
	 * @memberof FlattenedWorkstreamSummary
	 */
	ranges?: FlattenedRanges;
	/**
	 *
	 * @type {Model}
	 * @memberof FlattenedWorkstreamSummary
	 */
	model: Model;
	/**
	 *
	 * @type {FlattenedWebsites}
	 * @memberof FlattenedWorkstreamSummary
	 */
	websites?: FlattenedWebsites;
	/**
	 *
	 * @type {FlattenedAnchors}
	 * @memberof FlattenedWorkstreamSummary
	 */
	anchors?: FlattenedAnchors;
	/**
	 *
	 * @type {FlattenedAssets}
	 * @memberof FlattenedWorkstreamSummary
	 */
	assets?: FlattenedAssets;
	/**
	 *
	 * @type {FlattenedConversations}
	 * @memberof FlattenedWorkstreamSummary
	 */
	conversations?: FlattenedConversations;
	/**
	 *
	 * @type {FlattenedPersons}
	 * @memberof FlattenedWorkstreamSummary
	 */
	persons?: FlattenedPersons;
	/**
	 *
	 * @type {Applications}
	 * @memberof FlattenedWorkstreamSummary
	 */
	applications?: Applications;
}

/**
 * Check if a given object implements the FlattenedWorkstreamSummary interface.
 */
export function instanceOfFlattenedWorkstreamSummary(value: object): boolean {
	let isInstance = true;
	isInstance = isInstance && "id" in value;
	isInstance = isInstance && "created" in value;
	isInstance = isInstance && "updated" in value;
	isInstance = isInstance && "name" in value;
	isInstance = isInstance && "model" in value;

	return isInstance;
}

export function FlattenedWorkstreamSummaryFromJSON(
	json: any,
): FlattenedWorkstreamSummary {
	return FlattenedWorkstreamSummaryFromJSONTyped(json, false);
}

export function FlattenedWorkstreamSummaryFromJSONTyped(
	json: any,
	_ignoreDiscriminator: boolean,
): FlattenedWorkstreamSummary {
	if (json === undefined || json === null) {
		return json;
	}
	return {
		schema: exists(json, "schema")
			? EmbeddedModelSchemaFromJSON(json["schema"])
			: undefined,
		id: json["id"],
		score: exists(json, "score") ? ScoreFromJSON(json["score"]) : undefined,
		created: GroupedTimestampFromJSON(json["created"]),
		updated: GroupedTimestampFromJSON(json["updated"]),
		events: exists(json, "events")
			? FlattenedWorkstreamEventsFromJSON(json["events"])
			: undefined,
		name: json["name"],
		annotations: exists(json, "annotations")
			? FlattenedAnnotationsFromJSON(json["annotations"])
			: undefined,
		ranges: exists(json, "ranges")
			? FlattenedRangesFromJSON(json["ranges"])
			: undefined,
		model: ModelFromJSON(json["model"]),
		websites: exists(json, "websites")
			? FlattenedWebsitesFromJSON(json["websites"])
			: undefined,
		anchors: exists(json, "anchors")
			? FlattenedAnchorsFromJSON(json["anchors"])
			: undefined,
		assets: exists(json, "assets")
			? FlattenedAssetsFromJSON(json["assets"])
			: undefined,
		conversations: exists(json, "conversations")
			? FlattenedConversationsFromJSON(json["conversations"])
			: undefined,
		persons: exists(json, "persons")
			? FlattenedPersonsFromJSON(json["persons"])
			: undefined,
		applications: exists(json, "applications")
			? ApplicationsFromJSON(json["applications"])
			: undefined,
	};
}

export function FlattenedWorkstreamSummaryToJSON(
	value?: FlattenedWorkstreamSummary | null,
): any {
	if (value === undefined) {
		return undefined;
	}
	if (value === null) {
		return null;
	}
	return {
		schema: EmbeddedModelSchemaToJSON(value.schema),
		id: value.id,
		score: ScoreToJSON(value.score),
		created: GroupedTimestampToJSON(value.created),
		updated: GroupedTimestampToJSON(value.updated),
		events: FlattenedWorkstreamEventsToJSON(value.events),
		name: value.name,
		annotations: FlattenedAnnotationsToJSON(value.annotations),
		ranges: FlattenedRangesToJSON(value.ranges),
		model: ModelToJSON(value.model),
		websites: FlattenedWebsitesToJSON(value.websites),
		anchors: FlattenedAnchorsToJSON(value.anchors),
		assets: FlattenedAssetsToJSON(value.assets),
		conversations: FlattenedConversationsToJSON(value.conversations),
		persons: FlattenedPersonsToJSON(value.persons),
		applications: ApplicationsToJSON(value.applications),
	};
}
