/* tslint:disable */
/* eslint-disable */
/**
 * Pieces Isomorphic OpenAPI
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from "../runtime.ts";
import {
	EmbeddedModelSchemaFromJSON,
	EmbeddedModelSchemaToJSON,
	type EmbeddedModelSchema,
} from "./EmbeddedModelSchema.tsx";
import {
	ReferencedSensitiveFromJSON,
	ReferencedSensitiveToJSON,
	type ReferencedSensitive,
} from "./ReferencedSensitive.tsx";
import { ScoreFromJSON, ScoreToJSON, type Score } from "./Score.tsx";

/**
 * This is a flattened representation of multiple sensitive pieces of data.
 * @export
 * @interface FlattenedSensitives
 */
export interface FlattenedSensitives {
	/**
	 *
	 * @type {EmbeddedModelSchema}
	 * @memberof FlattenedSensitives
	 */
	schema?: EmbeddedModelSchema;
	/**
	 *
	 * @type {Array<ReferencedSensitive>}
	 * @memberof FlattenedSensitives
	 */
	iterable: ReferencedSensitive[];
	/**
	 *
	 * @type {Score}
	 * @memberof FlattenedSensitives
	 */
	score?: Score;
}

/**
 * Check if a given object implements the FlattenedSensitives interface.
 */
export function instanceOfFlattenedSensitives(value: object): boolean {
	let isInstance = true;
	isInstance = isInstance && "iterable" in value;

	return isInstance;
}

export function FlattenedSensitivesFromJSON(json: any): FlattenedSensitives {
	return FlattenedSensitivesFromJSONTyped(json, false);
}

export function FlattenedSensitivesFromJSONTyped(
	json: any,
	_ignoreDiscriminator: boolean,
): FlattenedSensitives {
	if (json === undefined || json === null) {
		return json;
	}
	return {
		schema: exists(json, "schema")
			? EmbeddedModelSchemaFromJSON(json["schema"])
			: undefined,
		iterable: (json["iterable"] as any[]).map(ReferencedSensitiveFromJSON),
		score: exists(json, "score") ? ScoreFromJSON(json["score"]) : undefined,
	};
}

export function FlattenedSensitivesToJSON(
	value?: FlattenedSensitives | null,
): any {
	if (value === undefined) {
		return undefined;
	}
	if (value === null) {
		return null;
	}
	return {
		schema: EmbeddedModelSchemaToJSON(value.schema),
		iterable: (value.iterable as any[]).map(ReferencedSensitiveToJSON),
		score: ScoreToJSON(value.score),
	};
}
