/* tslint:disable */
/* eslint-disable */
/**
 * Pieces Isomorphic OpenAPI
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from "../runtime.ts";
import type { EmbeddedModelSchema } from "./EmbeddedModelSchema.tsx";
import {
	EmbeddedModelSchemaFromJSON,
	EmbeddedModelSchemaToJSON,
} from "./EmbeddedModelSchema.tsx";
import type { ReferencedActivity } from "./ReferencedActivity.tsx";
import {
	ReferencedActivityFromJSON,
	ReferencedActivityToJSON,
} from "./ReferencedActivity.tsx";

/**
 *
 * @export
 * @interface FlattenedActivities
 */
export interface FlattenedActivities {
	/**
	 *
	 * @type {EmbeddedModelSchema}
	 * @memberof FlattenedActivities
	 */
	schema?: EmbeddedModelSchema;
	/**
	 *
	 * @type {Array<ReferencedActivity>}
	 * @memberof FlattenedActivities
	 */
	iterable: ReferencedActivity[];
}

/**
 * Check if a given object implements the FlattenedActivities interface.
 */
export function instanceOfFlattenedActivities(value: object): boolean {
	let isInstance = true;
	isInstance = isInstance && "iterable" in value;

	return isInstance;
}

export function FlattenedActivitiesFromJSON(json: any): FlattenedActivities {
	return FlattenedActivitiesFromJSONTyped(json, false);
}

export function FlattenedActivitiesFromJSONTyped(
	json: any,
	_ignoreDiscriminator: boolean,
): FlattenedActivities {
	if (json === undefined || json === null) {
		return json;
	}
	return {
		schema: exists(json, "schema")
			? EmbeddedModelSchemaFromJSON(json["schema"])
			: undefined,
		iterable: (json["iterable"] as any[]).map(ReferencedActivityFromJSON),
	};
}

export function FlattenedActivitiesToJSON(
	value?: FlattenedActivities | null,
): any {
	if (value === undefined) {
		return undefined;
	}
	if (value === null) {
		return null;
	}
	return {
		schema: EmbeddedModelSchemaToJSON(value.schema),
		iterable: (value.iterable as any[]).map(ReferencedActivityToJSON),
	};
}
