/* tslint:disable */
/* eslint-disable */
/**
 * Pieces Isomorphic OpenAPI
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from "../runtime.ts";
import {
	EmbeddedModelSchemaFromJSON,
	EmbeddedModelSchemaToJSON,
	type EmbeddedModelSchema,
} from "./EmbeddedModelSchema.tsx";
import {
	GraphicalOCRStatisticsFromJSON,
	GraphicalOCRStatisticsToJSON,
	type GraphicalOCRStatistics,
} from "./GraphicalOCRStatistics.tsx";

/**
 *
 * @export
 * @interface GraphicalOCRProcessing
 */
export interface GraphicalOCRProcessing {
	/**
	 *
	 * @type {EmbeddedModelSchema}
	 * @memberof GraphicalOCRProcessing
	 */
	schema?: EmbeddedModelSchema;
	/**
	 *
	 * @type {GraphicalOCRStatistics}
	 * @memberof GraphicalOCRProcessing
	 */
	statistics?: GraphicalOCRStatistics;
}

/**
 * Check if a given object implements the GraphicalOCRProcessing interface.
 */
export function instanceOfGraphicalOCRProcessing(_value: object): boolean {
	const isInstance = true;

	return isInstance;
}

export function GraphicalOCRProcessingFromJSON(
	json: any,
): GraphicalOCRProcessing {
	return GraphicalOCRProcessingFromJSONTyped(json, false);
}

export function GraphicalOCRProcessingFromJSONTyped(
	json: any,
	_ignoreDiscriminator: boolean,
): GraphicalOCRProcessing {
	if (json === undefined || json === null) {
		return json;
	}
	return {
		schema: exists(json, "schema")
			? EmbeddedModelSchemaFromJSON(json["schema"])
			: undefined,
		statistics: exists(json, "statistics")
			? GraphicalOCRStatisticsFromJSON(json["statistics"])
			: undefined,
	};
}

export function GraphicalOCRProcessingToJSON(
	value?: GraphicalOCRProcessing | null,
): any {
	if (value === undefined) {
		return undefined;
	}
	if (value === null) {
		return null;
	}
	return {
		schema: EmbeddedModelSchemaToJSON(value.schema),
		statistics: GraphicalOCRStatisticsToJSON(value.statistics),
	};
}
