/* tslint:disable */
/* eslint-disable */
/**
 * Pieces Isomorphic OpenAPI
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from "../runtime.ts";
import {
	EmbeddedModelSchemaFromJSON,
	EmbeddedModelSchemaToJSON,
	type EmbeddedModelSchema,
} from "./EmbeddedModelSchema.tsx";
import {
	OSHealthFromJSON,
	OSHealthToJSON,
	type OSHealth,
} from "./OSHealth.tsx";

/**
 * This is a health model used to determine the "health" of the os server and cloud server(Coming Soon). READONLY Model.
 * @export
 * @interface Health
 */
export interface Health {
	/**
	 *
	 * @type {EmbeddedModelSchema}
	 * @memberof Health
	 */
	schema?: EmbeddedModelSchema;
	/**
	 *
	 * @type {OSHealth}
	 * @memberof Health
	 */
	os: OSHealth;
}

/**
 * Check if a given object implements the Health interface.
 */
export function instanceOfHealth(value: object): boolean {
	let isInstance = true;
	isInstance = isInstance && "os" in value;

	return isInstance;
}

export function HealthFromJSON(json: any): Health {
	return HealthFromJSONTyped(json, false);
}

export function HealthFromJSONTyped(
	json: any,
	_ignoreDiscriminator: boolean,
): Health {
	if (json === undefined || json === null) {
		return json;
	}
	return {
		schema: exists(json, "schema")
			? EmbeddedModelSchemaFromJSON(json["schema"])
			: undefined,
		os: OSHealthFromJSON(json["os"]),
	};
}

export function HealthToJSON(value?: Health | null): any {
	if (value === undefined) {
		return undefined;
	}
	if (value === null) {
		return null;
	}
	return {
		schema: EmbeddedModelSchemaToJSON(value.schema),
		os: OSHealthToJSON(value.os),
	};
}
