/* tslint:disable */
/* eslint-disable */
/**
 * Pieces Isomorphic OpenAPI
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from "../runtime.ts";
import {
	EmbeddedModelSchemaFromJSON,
	EmbeddedModelSchemaToJSON,
	type EmbeddedModelSchema,
} from "./EmbeddedModelSchema.tsx";
import { HintFromJSON, HintToJSON, type Hint } from "./Hint.tsx";
import { ScoreFromJSON, ScoreToJSON, type Score } from "./Score.tsx";

/**
 * This is the plural of a Hint.
 * @export
 * @interface Hints
 */
export interface Hints {
	/**
	 *
	 * @type {EmbeddedModelSchema}
	 * @memberof Hints
	 */
	schema?: EmbeddedModelSchema;
	/**
	 *
	 * @type {Array<Hint>}
	 * @memberof Hints
	 */
	iterable: Hint[];
	/**
	 * This is a Map<String, int> where the the key is an hint id.
	 * @type {{ [key: string]: number; }}
	 * @memberof Hints
	 */
	indices?: { [key: string]: number };
	/**
	 *
	 * @type {Score}
	 * @memberof Hints
	 */
	score?: Score;
}

/**
 * Check if a given object implements the Hints interface.
 */
export function instanceOfHints(value: object): boolean {
	let isInstance = true;
	isInstance = isInstance && "iterable" in value;

	return isInstance;
}

export function HintsFromJSON(json: any): Hints {
	return HintsFromJSONTyped(json, false);
}

export function HintsFromJSONTyped(
	json: any,
	_ignoreDiscriminator: boolean,
): Hints {
	if (json === undefined || json === null) {
		return json;
	}
	return {
		schema: exists(json, "schema")
			? EmbeddedModelSchemaFromJSON(json["schema"])
			: undefined,
		iterable: (json["iterable"] as any[]).map(HintFromJSON),
		indices: exists(json, "indices") ? json["indices"] : undefined,
		score: exists(json, "score") ? ScoreFromJSON(json["score"]) : undefined,
	};
}

export function HintsToJSON(value?: Hints | null): any {
	if (value === undefined) {
		return undefined;
	}
	if (value === null) {
		return null;
	}
	return {
		schema: EmbeddedModelSchemaToJSON(value.schema),
		iterable: (value.iterable as any[]).map(HintToJSON),
		indices: value.indices,
		score: ScoreToJSON(value.score),
	};
}
