/* tslint:disable */
/* eslint-disable */
/**
 * Pieces Isomorphic OpenAPI
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from "../runtime.ts";
import type { EmbeddedModelSchema } from "./EmbeddedModelSchema.tsx";
import {
	EmbeddedModelSchemaFromJSON,
	EmbeddedModelSchemaToJSON,
} from "./EmbeddedModelSchema.tsx";
import type { IDETab } from "./IDETab.tsx";
import { IDETabFromJSON, IDETabToJSON } from "./IDETab.tsx";

/**
 * This is a plural representation of a IDETab
 * @export
 * @interface IDETabs
 */
export interface IDETabs {
	/**
	 *
	 * @type {EmbeddedModelSchema}
	 * @memberof IDETabs
	 */
	schema?: EmbeddedModelSchema;
	/**
	 *
	 * @type {Array<IDETab>}
	 * @memberof IDETabs
	 */
	iterable: IDETab[];
}

/**
 * Check if a given object implements the IDETabs interface.
 */
export function instanceOfIDETabs(value: object): boolean {
	let isInstance = true;
	isInstance = isInstance && "iterable" in value;

	return isInstance;
}

export function IDETabsFromJSON(json: any): IDETabs {
	return IDETabsFromJSONTyped(json, false);
}

export function IDETabsFromJSONTyped(
	json: any,
	_ignoreDiscriminator: boolean,
): IDETabs {
	if (json === undefined || json === null) {
		return json;
	}
	return {
		schema: exists(json, "schema")
			? EmbeddedModelSchemaFromJSON(json["schema"])
			: undefined,
		iterable: (json["iterable"] as any[]).map(IDETabFromJSON),
	};
}

export function IDETabsToJSON(value?: IDETabs | null): any {
	if (value === undefined) {
		return undefined;
	}
	if (value === null) {
		return null;
	}
	return {
		schema: EmbeddedModelSchemaToJSON(value.schema),
		iterable: (value.iterable as any[]).map(IDETabToJSON),
	};
}
