/* tslint:disable */
/* eslint-disable */
/**
 * Pieces Isomorphic OpenAPI
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from "../runtime.ts";
import {
	EmbeddedModelSchemaFromJSON,
	EmbeddedModelSchemaToJSON,
	type EmbeddedModelSchema,
} from "./EmbeddedModelSchema.tsx";
import {
	LanguageServerProtocolDiagnosticFromJSON,
	LanguageServerProtocolDiagnosticToJSON,
	type LanguageServerProtocolDiagnostic,
} from "./LanguageServerProtocolDiagnostic.tsx";

/**
 * TODO
 * @export
 * @interface LanguageServerProtocolDiagnostics
 */
export interface LanguageServerProtocolDiagnostics {
	/**
	 *
	 * @type {EmbeddedModelSchema}
	 * @memberof LanguageServerProtocolDiagnostics
	 */
	schema?: EmbeddedModelSchema;
	/**
	 *
	 * @type {Array<LanguageServerProtocolDiagnostic>}
	 * @memberof LanguageServerProtocolDiagnostics
	 */
	iterable: LanguageServerProtocolDiagnostic[];
}

/**
 * Check if a given object implements the LanguageServerProtocolDiagnostics interface.
 */
export function instanceOfLanguageServerProtocolDiagnostics(
	value: object,
): boolean {
	let isInstance = true;
	isInstance = isInstance && "iterable" in value;

	return isInstance;
}

export function LanguageServerProtocolDiagnosticsFromJSON(
	json: any,
): LanguageServerProtocolDiagnostics {
	return LanguageServerProtocolDiagnosticsFromJSONTyped(json, false);
}

export function LanguageServerProtocolDiagnosticsFromJSONTyped(
	json: any,
	_ignoreDiscriminator: boolean,
): LanguageServerProtocolDiagnostics {
	if (json === undefined || json === null) {
		return json;
	}
	return {
		schema: exists(json, "schema")
			? EmbeddedModelSchemaFromJSON(json["schema"])
			: undefined,
		iterable: (json["iterable"] as any[]).map(
			LanguageServerProtocolDiagnosticFromJSON,
		),
	};
}

export function LanguageServerProtocolDiagnosticsToJSON(
	value?: LanguageServerProtocolDiagnostics | null,
): any {
	if (value === undefined) {
		return undefined;
	}
	if (value === null) {
		return null;
	}
	return {
		schema: EmbeddedModelSchemaToJSON(value.schema),
		iterable: (value.iterable as any[]).map(
			LanguageServerProtocolDiagnosticToJSON,
		),
	};
}
