/* tslint:disable */
/* eslint-disable */
/**
 * Pieces Isomorphic OpenAPI
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from "../runtime.ts";
import {
	EmbeddedModelSchemaFromJSON,
	EmbeddedModelSchemaToJSON,
	type EmbeddedModelSchema,
} from "./EmbeddedModelSchema.tsx";
import { RangeFromJSON, RangeToJSON, type Range } from "./Range.tsx";
import { ScoreFromJSON, ScoreToJSON, type Score } from "./Score.tsx";

/**
 * This is a collection of many Ranges
 * @export
 * @interface Ranges
 */
export interface Ranges {
	/**
	 *
	 * @type {EmbeddedModelSchema}
	 * @memberof Ranges
	 */
	schema?: EmbeddedModelSchema;
	/**
	 *
	 * @type {Array<Range>}
	 * @memberof Ranges
	 */
	iterable: Range[];
	/**
	 * This is a Map<String, int> where the the key is an range id.
	 * @type {{ [key: string]: number; }}
	 * @memberof Ranges
	 */
	indices?: { [key: string]: number };
	/**
	 *
	 * @type {Score}
	 * @memberof Ranges
	 */
	score?: Score;
	/**
	 *
	 * @type {boolean}
	 * @memberof Ranges
	 */
	continuous?: boolean;
}

/**
 * Check if a given object implements the Ranges interface.
 */
export function instanceOfRanges(value: object): boolean {
	let isInstance = true;
	isInstance = isInstance && "iterable" in value;

	return isInstance;
}

export function RangesFromJSON(json: any): Ranges {
	return RangesFromJSONTyped(json, false);
}

export function RangesFromJSONTyped(
	json: any,
	_ignoreDiscriminator: boolean,
): Ranges {
	if (json === undefined || json === null) {
		return json;
	}
	return {
		schema: exists(json, "schema")
			? EmbeddedModelSchemaFromJSON(json["schema"])
			: undefined,
		iterable: (json["iterable"] as any[]).map(RangeFromJSON),
		indices: exists(json, "indices") ? json["indices"] : undefined,
		score: exists(json, "score") ? ScoreFromJSON(json["score"]) : undefined,
		continuous: exists(json, "continuous") ? json["continuous"] : undefined,
	};
}

export function RangesToJSON(value?: Ranges | null): any {
	if (value === undefined) {
		return undefined;
	}
	if (value === null) {
		return null;
	}
	return {
		schema: EmbeddedModelSchemaToJSON(value.schema),
		iterable: (value.iterable as any[]).map(RangeToJSON),
		indices: value.indices,
		score: ScoreToJSON(value.score),
		continuous: value.continuous,
	};
}
