/* tslint:disable */
/* eslint-disable */
/**
 * Pieces Isomorphic OpenAPI
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from "../runtime.ts";
import {
	EmbeddedModelSchemaFromJSON,
	EmbeddedModelSchemaToJSON,
	type EmbeddedModelSchema,
} from "./EmbeddedModelSchema.tsx";
import {
	PersonBasicTypeFromJSON,
	PersonBasicTypeToJSON,
	type PersonBasicType,
} from "./PersonBasicType.tsx";

/**
 * This an iterable of People that are attached to a specific distribution ie, slack, maigun, ...etc
 * @export
 * @interface Recipients
 */
export interface Recipients {
	/**
	 *
	 * @type {Array<PersonBasicType>}
	 * @memberof Recipients
	 */
	iterable: PersonBasicType[];
	/**
	 *
	 * @type {EmbeddedModelSchema}
	 * @memberof Recipients
	 */
	schema?: EmbeddedModelSchema;
}

/**
 * Check if a given object implements the Recipients interface.
 */
export function instanceOfRecipients(value: object): boolean {
	let isInstance = true;
	isInstance = isInstance && "iterable" in value;

	return isInstance;
}

export function RecipientsFromJSON(json: any): Recipients {
	return RecipientsFromJSONTyped(json, false);
}

export function RecipientsFromJSONTyped(
	json: any,
	_ignoreDiscriminator: boolean,
): Recipients {
	if (json === undefined || json === null) {
		return json;
	}
	return {
		iterable: (json["iterable"] as any[]).map(PersonBasicTypeFromJSON),
		schema: exists(json, "schema")
			? EmbeddedModelSchemaFromJSON(json["schema"])
			: undefined,
	};
}

export function RecipientsToJSON(value?: Recipients | null): any {
	if (value === undefined) {
		return undefined;
	}
	if (value === null) {
		return null;
	}
	return {
		iterable: (value.iterable as any[]).map(PersonBasicTypeToJSON),
		schema: EmbeddedModelSchemaToJSON(value.schema),
	};
}
