/* tslint:disable */
/* eslint-disable */
/**
 * Pieces Isomorphic OpenAPI
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from "../runtime.ts";
import {
	EmbeddedModelSchemaFromJSON,
	EmbeddedModelSchemaToJSON,
	type EmbeddedModelSchema,
} from "./EmbeddedModelSchema.tsx";
import {
	RelevantQGPTSeedFromJSON,
	RelevantQGPTSeedToJSON,
	type RelevantQGPTSeed,
} from "./RelevantQGPTSeed.tsx";

/**
 * This is a plural of RelevantQGPTSeed.
 * @export
 * @interface RelevantQGPTSeeds
 */
export interface RelevantQGPTSeeds {
	/**
	 *
	 * @type {EmbeddedModelSchema}
	 * @memberof RelevantQGPTSeeds
	 */
	schema?: EmbeddedModelSchema;
	/**
	 *
	 * @type {Array<RelevantQGPTSeed>}
	 * @memberof RelevantQGPTSeeds
	 */
	iterable: RelevantQGPTSeed[];
}

/**
 * Check if a given object implements the RelevantQGPTSeeds interface.
 */
export function instanceOfRelevantQGPTSeeds(value: object): boolean {
	let isInstance = true;
	isInstance = isInstance && "iterable" in value;

	return isInstance;
}

export function RelevantQGPTSeedsFromJSON(json: any): RelevantQGPTSeeds {
	return RelevantQGPTSeedsFromJSONTyped(json, false);
}

export function RelevantQGPTSeedsFromJSONTyped(
	json: any,
	_ignoreDiscriminator: boolean,
): RelevantQGPTSeeds {
	if (json === undefined || json === null) {
		return json;
	}
	return {
		schema: exists(json, "schema")
			? EmbeddedModelSchemaFromJSON(json["schema"])
			: undefined,
		iterable: (json["iterable"] as any[]).map(RelevantQGPTSeedFromJSON),
	};
}

export function RelevantQGPTSeedsToJSON(value?: RelevantQGPTSeeds | null): any {
	if (value === undefined) {
		return undefined;
	}
	if (value === null) {
		return null;
	}
	return {
		schema: EmbeddedModelSchemaToJSON(value.schema),
		iterable: (value.iterable as any[]).map(RelevantQGPTSeedToJSON),
	};
}
