/* tslint:disable */
/* eslint-disable */
/**
 * Pieces Isomorphic OpenAPI
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from "../runtime.ts";
import type { EmbeddedModelSchema } from "./EmbeddedModelSchema.tsx";
import {
	EmbeddedModelSchemaFromJSON,
	EmbeddedModelSchemaToJSON,
} from "./EmbeddedModelSchema.tsx";
import type { SearchedConversationMessage } from "./SearchedConversationMessage.tsx";
import {
	SearchedConversationMessageFromJSON,
	SearchedConversationMessageToJSON,
} from "./SearchedConversationMessage.tsx";

/**
 * This is the plural Model used to return many SearchedConversationMessage.
 * @export
 * @interface SearchedConversationMessages
 */
export interface SearchedConversationMessages {
	/**
	 *
	 * @type {EmbeddedModelSchema}
	 * @memberof SearchedConversationMessages
	 */
	schema?: EmbeddedModelSchema;
	/**
	 *
	 * @type {Array<SearchedConversationMessage>}
	 * @memberof SearchedConversationMessages
	 */
	iterable: SearchedConversationMessage[];
}

/**
 * Check if a given object implements the SearchedConversationMessages interface.
 */
export function instanceOfSearchedConversationMessages(value: object): boolean {
	let isInstance = true;
	isInstance = isInstance && "iterable" in value;

	return isInstance;
}

export function SearchedConversationMessagesFromJSON(
	json: any,
): SearchedConversationMessages {
	return SearchedConversationMessagesFromJSONTyped(json, false);
}

export function SearchedConversationMessagesFromJSONTyped(
	json: any,
	_ignoreDiscriminator: boolean,
): SearchedConversationMessages {
	if (json === undefined || json === null) {
		return json;
	}
	return {
		schema: exists(json, "schema")
			? EmbeddedModelSchemaFromJSON(json["schema"])
			: undefined,
		iterable: (json["iterable"] as any[]).map(
			SearchedConversationMessageFromJSON,
		),
	};
}

export function SearchedConversationMessagesToJSON(
	value?: SearchedConversationMessages | null,
): any {
	if (value === undefined) {
		return undefined;
	}
	if (value === null) {
		return null;
	}
	return {
		schema: EmbeddedModelSchemaToJSON(value.schema),
		iterable: (value.iterable as any[]).map(
			SearchedConversationMessageToJSON,
		),
	};
}
