/* tslint:disable */
/* eslint-disable */
/**
 * Pieces Isomorphic OpenAPI
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from "../runtime.ts";
import type { Annotation } from "./Annotation.tsx";
import { AnnotationFromJSON, AnnotationToJSON } from "./Annotation.tsx";
import type { EmbeddedModelSchema } from "./EmbeddedModelSchema.tsx";
import {
	EmbeddedModelSchemaFromJSON,
	EmbeddedModelSchemaToJSON,
} from "./EmbeddedModelSchema.tsx";

/**
 * This is used for the Annotation searching endpoint
 *
 * annotation here is only provided if transferables are set to true.
 *
 * temporal: if this is provided this means that their material matched the input via a timestamp.
 *
 * TODO will want to consider returning related materials to this material potentially both associated/ and not associated materials
 * ie suggestion: WorkstreamSuggestions
 * @export
 * @interface SearchedAnnotation
 */
export interface SearchedAnnotation {
	/**
	 *
	 * @type {EmbeddedModelSchema}
	 * @memberof SearchedAnnotation
	 */
	schema?: EmbeddedModelSchema;
	/**
	 *
	 * @type {Annotation}
	 * @memberof SearchedAnnotation
	 */
	annotation?: Annotation;
	/**
	 *
	 * @type {boolean}
	 * @memberof SearchedAnnotation
	 */
	exact: boolean;
	/**
	 *
	 * @type {number}
	 * @memberof SearchedAnnotation
	 */
	similarity: number;
	/**
	 *
	 * @type {boolean}
	 * @memberof SearchedAnnotation
	 */
	temporal?: boolean;
	/**
	 * This is the uuid of the annotation.
	 * @type {string}
	 * @memberof SearchedAnnotation
	 */
	identifier: string;
}

/**
 * Check if a given object implements the SearchedAnnotation interface.
 */
export function instanceOfSearchedAnnotation(value: object): boolean {
	let isInstance = true;
	isInstance = isInstance && "exact" in value;
	isInstance = isInstance && "similarity" in value;
	isInstance = isInstance && "identifier" in value;

	return isInstance;
}

export function SearchedAnnotationFromJSON(json: any): SearchedAnnotation {
	return SearchedAnnotationFromJSONTyped(json, false);
}

export function SearchedAnnotationFromJSONTyped(
	json: any,
	_ignoreDiscriminator: boolean,
): SearchedAnnotation {
	if (json === undefined || json === null) {
		return json;
	}
	return {
		schema: exists(json, "schema")
			? EmbeddedModelSchemaFromJSON(json["schema"])
			: undefined,
		annotation: exists(json, "annotation")
			? AnnotationFromJSON(json["annotation"])
			: undefined,
		exact: json["exact"],
		similarity: json["similarity"],
		temporal: exists(json, "temporal") ? json["temporal"] : undefined,
		identifier: json["identifier"],
	};
}

export function SearchedAnnotationToJSON(
	value?: SearchedAnnotation | null,
): any {
	if (value === undefined) {
		return undefined;
	}
	if (value === null) {
		return null;
	}
	return {
		schema: EmbeddedModelSchemaToJSON(value.schema),
		annotation: AnnotationToJSON(value.annotation),
		exact: value.exact,
		similarity: value.similarity,
		temporal: value.temporal,
		identifier: value.identifier,
	};
}
