/* tslint:disable */
/* eslint-disable */
/**
 * Pieces Isomorphic OpenAPI
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from "../runtime.ts";
import {
	EmbeddedModelSchemaFromJSON,
	EmbeddedModelSchemaToJSON,
	type EmbeddedModelSchema,
} from "./EmbeddedModelSchema.tsx";
import {
	SearchedWorkstreamPatternEngineVisionEventFromJSON,
	SearchedWorkstreamPatternEngineVisionEventToJSON,
	type SearchedWorkstreamPatternEngineVisionEvent,
} from "./SearchedWorkstreamPatternEngineVisionEvent.tsx";

/**
 * This will return a list of the returned events.
 * @export
 * @interface SearchedWorkstreamPatternEngineVisionEvents
 */
export interface SearchedWorkstreamPatternEngineVisionEvents {
	/**
	 *
	 * @type {EmbeddedModelSchema}
	 * @memberof SearchedWorkstreamPatternEngineVisionEvents
	 */
	schema?: EmbeddedModelSchema;
	/**
	 *
	 * @type {Array<SearchedWorkstreamPatternEngineVisionEvent>}
	 * @memberof SearchedWorkstreamPatternEngineVisionEvents
	 */
	iterable: SearchedWorkstreamPatternEngineVisionEvent[];
}

/**
 * Check if a given object implements the SearchedWorkstreamPatternEngineVisionEvents interface.
 */
export function instanceOfSearchedWorkstreamPatternEngineVisionEvents(
	value: object,
): boolean {
	let isInstance = true;
	isInstance = isInstance && "iterable" in value;

	return isInstance;
}

export function SearchedWorkstreamPatternEngineVisionEventsFromJSON(
	json: any,
): SearchedWorkstreamPatternEngineVisionEvents {
	return SearchedWorkstreamPatternEngineVisionEventsFromJSONTyped(
		json,
		false,
	);
}

export function SearchedWorkstreamPatternEngineVisionEventsFromJSONTyped(
	json: any,
	_ignoreDiscriminator: boolean,
): SearchedWorkstreamPatternEngineVisionEvents {
	if (json === undefined || json === null) {
		return json;
	}
	return {
		schema: exists(json, "schema")
			? EmbeddedModelSchemaFromJSON(json["schema"])
			: undefined,
		iterable: (json["iterable"] as any[]).map(
			SearchedWorkstreamPatternEngineVisionEventFromJSON,
		),
	};
}

export function SearchedWorkstreamPatternEngineVisionEventsToJSON(
	value?: SearchedWorkstreamPatternEngineVisionEvents | null,
): any {
	if (value === undefined) {
		return undefined;
	}
	if (value === null) {
		return null;
	}
	return {
		schema: EmbeddedModelSchemaToJSON(value.schema),
		iterable: (value.iterable as any[]).map(
			SearchedWorkstreamPatternEngineVisionEventToJSON,
		),
	};
}
