/* tslint:disable */
/* eslint-disable */
/**
 * Pieces Isomorphic OpenAPI
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from "../runtime.ts";
import type { EmbeddedModelSchema } from "./EmbeddedModelSchema.tsx";
import {
	EmbeddedModelSchemaFromJSON,
	EmbeddedModelSchemaToJSON,
} from "./EmbeddedModelSchema.tsx";
import type { SearchedWorkstreamSummary } from "./SearchedWorkstreamSummary.tsx";
import {
	SearchedWorkstreamSummaryFromJSON,
	SearchedWorkstreamSummaryToJSON,
} from "./SearchedWorkstreamSummary.tsx";

/**
 * This is the plural Model used to return many SearchedWorkstreamSummary.
 * @export
 * @interface SearchedWorkstreamSummaries
 */
export interface SearchedWorkstreamSummaries {
	/**
	 *
	 * @type {EmbeddedModelSchema}
	 * @memberof SearchedWorkstreamSummaries
	 */
	schema?: EmbeddedModelSchema;
	/**
	 *
	 * @type {Array<SearchedWorkstreamSummary>}
	 * @memberof SearchedWorkstreamSummaries
	 */
	iterable: SearchedWorkstreamSummary[];
}

/**
 * Check if a given object implements the SearchedWorkstreamSummaries interface.
 */
export function instanceOfSearchedWorkstreamSummaries(value: object): boolean {
	let isInstance = true;
	isInstance = isInstance && "iterable" in value;

	return isInstance;
}

export function SearchedWorkstreamSummariesFromJSON(
	json: any,
): SearchedWorkstreamSummaries {
	return SearchedWorkstreamSummariesFromJSONTyped(json, false);
}

export function SearchedWorkstreamSummariesFromJSONTyped(
	json: any,
	_ignoreDiscriminator: boolean,
): SearchedWorkstreamSummaries {
	if (json === undefined || json === null) {
		return json;
	}
	return {
		schema: exists(json, "schema")
			? EmbeddedModelSchemaFromJSON(json["schema"])
			: undefined,
		iterable: (json["iterable"] as any[]).map(
			SearchedWorkstreamSummaryFromJSON,
		),
	};
}

export function SearchedWorkstreamSummariesToJSON(
	value?: SearchedWorkstreamSummaries | null,
): any {
	if (value === undefined) {
		return undefined;
	}
	if (value === null) {
		return null;
	}
	return {
		schema: EmbeddedModelSchemaToJSON(value.schema),
		iterable: (value.iterable as any[]).map(
			SearchedWorkstreamSummaryToJSON,
		),
	};
}
