/* tslint:disable */
/* eslint-disable */
/**
 * Pieces Isomorphic OpenAPI
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from "../runtime.ts";
import type { AnalyticsTrackedAdoptionEventIdentifierDescriptionPairs } from "./AnalyticsTrackedAdoptionEventIdentifierDescriptionPairs.tsx";
import {
	AnalyticsTrackedAdoptionEventIdentifierDescriptionPairsFromJSON,
	AnalyticsTrackedAdoptionEventIdentifierDescriptionPairsToJSON,
} from "./AnalyticsTrackedAdoptionEventIdentifierDescriptionPairs.tsx";
import type { EmbeddedModelSchema } from "./EmbeddedModelSchema.tsx";
import {
	EmbeddedModelSchemaFromJSON,
	EmbeddedModelSchemaToJSON,
} from "./EmbeddedModelSchema.tsx";

/**
 *
 * @export
 * @interface SeededTrackedAdoptionEvent
 */
export interface SeededTrackedAdoptionEvent {
	/**
	 *
	 * @type {EmbeddedModelSchema}
	 * @memberof SeededTrackedAdoptionEvent
	 */
	schema?: EmbeddedModelSchema;
	/**
	 *
	 * @type {AnalyticsTrackedAdoptionEventIdentifierDescriptionPairs}
	 * @memberof SeededTrackedAdoptionEvent
	 */
	identifierDescriptionPair?: AnalyticsTrackedAdoptionEventIdentifierDescriptionPairs;
}

/**
 * Check if a given object implements the SeededTrackedAdoptionEvent interface.
 */
export function instanceOfSeededTrackedAdoptionEvent(_value: object): boolean {
	const isInstance = true;

	return isInstance;
}

export function SeededTrackedAdoptionEventFromJSON(
	json: any,
): SeededTrackedAdoptionEvent {
	return SeededTrackedAdoptionEventFromJSONTyped(json, false);
}

export function SeededTrackedAdoptionEventFromJSONTyped(
	json: any,
	_ignoreDiscriminator: boolean,
): SeededTrackedAdoptionEvent {
	if (json === undefined || json === null) {
		return json;
	}
	return {
		schema: exists(json, "schema")
			? EmbeddedModelSchemaFromJSON(json["schema"])
			: undefined,
		identifierDescriptionPair: exists(json, "identifier_description_pair")
			? AnalyticsTrackedAdoptionEventIdentifierDescriptionPairsFromJSON(
					json["identifier_description_pair"],
				)
			: undefined,
	};
}

export function SeededTrackedAdoptionEventToJSON(
	value?: SeededTrackedAdoptionEvent | null,
): any {
	if (value === undefined) {
		return undefined;
	}
	if (value === null) {
		return null;
	}
	return {
		schema: EmbeddedModelSchemaToJSON(value.schema),
		identifier_description_pair:
			AnalyticsTrackedAdoptionEventIdentifierDescriptionPairsToJSON(
				value.identifierDescriptionPair,
			),
	};
}
