/* tslint:disable */
/* eslint-disable */
/**
 * Pieces Isomorphic OpenAPI
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from "../runtime.ts";
import {
	EmbeddedModelSchemaFromJSON,
	EmbeddedModelSchemaToJSON,
	type EmbeddedModelSchema,
} from "./EmbeddedModelSchema.tsx";
import {
	MailgunDistributionFromJSON,
	MailgunDistributionToJSON,
	type MailgunDistribution,
} from "./MailgunDistribution.tsx";
import {
	SeededGitHubDistributionFromJSON,
	SeededGitHubDistributionToJSON,
	type SeededGitHubDistribution,
} from "./SeededGitHubDistribution.tsx";

/**
 * TODO if we add another distribution add to this, Distribution, and flattenedDistribution.
 *
 * can only use this Model with our Linkify Model.
 * @export
 * @interface SeededDistribution
 */
export interface SeededDistribution {
	/**
	 *
	 * @type {EmbeddedModelSchema}
	 * @memberof SeededDistribution
	 */
	schema?: EmbeddedModelSchema;
	/**
	 *
	 * @type {MailgunDistribution}
	 * @memberof SeededDistribution
	 */
	mailgun?: MailgunDistribution;
	/**
	 *
	 * @type {SeededGitHubDistribution}
	 * @memberof SeededDistribution
	 */
	github?: SeededGitHubDistribution;
}

/**
 * Check if a given object implements the SeededDistribution interface.
 */
export function instanceOfSeededDistribution(_value: object): boolean {
	const isInstance = true;

	return isInstance;
}

export function SeededDistributionFromJSON(json: any): SeededDistribution {
	return SeededDistributionFromJSONTyped(json, false);
}

export function SeededDistributionFromJSONTyped(
	json: any,
	_ignoreDiscriminator: boolean,
): SeededDistribution {
	if (json === undefined || json === null) {
		return json;
	}
	return {
		schema: exists(json, "schema")
			? EmbeddedModelSchemaFromJSON(json["schema"])
			: undefined,
		mailgun: exists(json, "mailgun")
			? MailgunDistributionFromJSON(json["mailgun"])
			: undefined,
		github: exists(json, "github")
			? SeededGitHubDistributionFromJSON(json["github"])
			: undefined,
	};
}

export function SeededDistributionToJSON(
	value?: SeededDistribution | null,
): any {
	if (value === undefined) {
		return undefined;
	}
	if (value === null) {
		return null;
	}
	return {
		schema: EmbeddedModelSchemaToJSON(value.schema),
		mailgun: MailgunDistributionToJSON(value.mailgun),
		github: SeededGitHubDistributionToJSON(value.github),
	};
}
