/* tslint:disable */
/* eslint-disable */
/**
 * Pieces Isomorphic OpenAPI
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from "../runtime.ts";
import {
	ApplicationFromJSON,
	ApplicationToJSON,
	type Application,
} from "./Application.tsx";
import {
	AvailableFormatsFromJSON,
	AvailableFormatsToJSON,
	type AvailableFormats,
} from "./AvailableFormats.tsx";
import {
	EmbeddedModelSchemaFromJSON,
	EmbeddedModelSchemaToJSON,
	type EmbeddedModelSchema,
} from "./EmbeddedModelSchema.tsx";
import {
	SeededAssetEnrichmentFromJSON,
	SeededAssetEnrichmentToJSON,
	type SeededAssetEnrichment,
} from "./SeededAssetEnrichment.tsx";
import {
	SeededAssetMetadataFromJSON,
	SeededAssetMetadataToJSON,
	type SeededAssetMetadata,
} from "./SeededAssetMetadata.tsx";
import {
	SeededFormatFromJSON,
	SeededFormatToJSON,
	type SeededFormat,
} from "./SeededFormat.tsx";

/**
 * This is seed data that will be come an asset.
 *
 * discovered: if set to true this seededAsset was discovered using one of our discovery endpoints.
 *
 * pseudo: if this is an asset that a user did NOT explicitly save.
 *
 * available: This is a model that is used within our '/assets/draft' endpoint that will emitt a seed with all the available format that one can generate based on the original seed that was passed in. ie if a png was passed in, we may  say that there is a text/code format available. If available formats is passed into the '/assets/create' we will short curcuit certain operations to speed up the process, for instance, if we determine that there is no text within this image then there is no sense in running ocr.
 *
 * @export
 * @interface SeededAsset
 */
export interface SeededAsset {
	/**
	 *
	 * @type {EmbeddedModelSchema}
	 * @memberof SeededAsset
	 */
	schema?: EmbeddedModelSchema;
	/**
	 *
	 * @type {SeededAssetMetadata}
	 * @memberof SeededAsset
	 */
	metadata?: SeededAssetMetadata;
	/**
	 *
	 * @type {Application}
	 * @memberof SeededAsset
	 */
	application: Application;
	/**
	 *
	 * @type {SeededFormat}
	 * @memberof SeededAsset
	 */
	format: SeededFormat;
	/**
	 *
	 * @type {boolean}
	 * @memberof SeededAsset
	 */
	discovered?: boolean;
	/**
	 *
	 * @type {AvailableFormats}
	 * @memberof SeededAsset
	 */
	available?: AvailableFormats;
	/**
	 *
	 * @type {boolean}
	 * @memberof SeededAsset
	 */
	pseudo?: boolean;
	/**
	 *
	 * @type {SeededAssetEnrichment}
	 * @memberof SeededAsset
	 */
	enrichment?: SeededAssetEnrichment;
	/**
	 * This will let us know if this asset was generated as a 'demo' snippet
	 * @type {boolean}
	 * @memberof SeededAsset
	 */
	demo?: boolean;
}

/**
 * Check if a given object implements the SeededAsset interface.
 */
export function instanceOfSeededAsset(value: object): boolean {
	let isInstance = true;
	isInstance = isInstance && "application" in value;
	isInstance = isInstance && "format" in value;

	return isInstance;
}

export function SeededAssetFromJSON(json: any): SeededAsset {
	return SeededAssetFromJSONTyped(json, false);
}

export function SeededAssetFromJSONTyped(
	json: any,
	_ignoreDiscriminator: boolean,
): SeededAsset {
	if (json === undefined || json === null) {
		return json;
	}
	return {
		schema: exists(json, "schema")
			? EmbeddedModelSchemaFromJSON(json["schema"])
			: undefined,
		metadata: exists(json, "metadata")
			? SeededAssetMetadataFromJSON(json["metadata"])
			: undefined,
		application: ApplicationFromJSON(json["application"]),
		format: SeededFormatFromJSON(json["format"]),
		discovered: exists(json, "discovered") ? json["discovered"] : undefined,
		available: exists(json, "available")
			? AvailableFormatsFromJSON(json["available"])
			: undefined,
		pseudo: exists(json, "pseudo") ? json["pseudo"] : undefined,
		enrichment: exists(json, "enrichment")
			? SeededAssetEnrichmentFromJSON(json["enrichment"])
			: undefined,
		demo: exists(json, "demo") ? json["demo"] : undefined,
	};
}

export function SeededAssetToJSON(value?: SeededAsset | null): any {
	if (value === undefined) {
		return undefined;
	}
	if (value === null) {
		return null;
	}
	return {
		schema: EmbeddedModelSchemaToJSON(value.schema),
		metadata: SeededAssetMetadataToJSON(value.metadata),
		application: ApplicationToJSON(value.application),
		format: SeededFormatToJSON(value.format),
		discovered: value.discovered,
		available: AvailableFormatsToJSON(value.available),
		pseudo: value.pseudo,
		enrichment: SeededAssetEnrichmentToJSON(value.enrichment),
		demo: value.demo,
	};
}
