/* tslint:disable */
/* eslint-disable */
/**
 * Pieces Isomorphic OpenAPI
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from "../runtime.ts";
import type { EmbeddedModelSchema } from "./EmbeddedModelSchema.tsx";
import {
	EmbeddedModelSchemaFromJSON,
	EmbeddedModelSchemaToJSON,
} from "./EmbeddedModelSchema.tsx";
import type { SeededDiscoverableRelatedTag } from "./SeededDiscoverableRelatedTag.tsx";
import {
	SeededDiscoverableRelatedTagFromJSON,
	SeededDiscoverableRelatedTagToJSON,
} from "./SeededDiscoverableRelatedTag.tsx";

/**
 *
 * @export
 * @interface SeededDiscoverableRelatedTags
 */
export interface SeededDiscoverableRelatedTags {
	/**
	 *
	 * @type {EmbeddedModelSchema}
	 * @memberof SeededDiscoverableRelatedTags
	 */
	schema?: EmbeddedModelSchema;
	/**
	 *
	 * @type {Array<SeededDiscoverableRelatedTag>}
	 * @memberof SeededDiscoverableRelatedTags
	 */
	iterable: SeededDiscoverableRelatedTag[];
	/**
	 * This is the application id that this request is sent from.
	 * @type {string}
	 * @memberof SeededDiscoverableRelatedTags
	 */
	application: string;
}

/**
 * Check if a given object implements the SeededDiscoverableRelatedTags interface.
 */
export function instanceOfSeededDiscoverableRelatedTags(
	value: object,
): boolean {
	let isInstance = true;
	isInstance = isInstance && "iterable" in value;
	isInstance = isInstance && "application" in value;

	return isInstance;
}

export function SeededDiscoverableRelatedTagsFromJSON(
	json: any,
): SeededDiscoverableRelatedTags {
	return SeededDiscoverableRelatedTagsFromJSONTyped(json, false);
}

export function SeededDiscoverableRelatedTagsFromJSONTyped(
	json: any,
	_ignoreDiscriminator: boolean,
): SeededDiscoverableRelatedTags {
	if (json === undefined || json === null) {
		return json;
	}
	return {
		schema: exists(json, "schema")
			? EmbeddedModelSchemaFromJSON(json["schema"])
			: undefined,
		iterable: (json["iterable"] as any[]).map(
			SeededDiscoverableRelatedTagFromJSON,
		),
		application: json["application"],
	};
}

export function SeededDiscoverableRelatedTagsToJSON(
	value?: SeededDiscoverableRelatedTags | null,
): any {
	if (value === undefined) {
		return undefined;
	}
	if (value === null) {
		return null;
	}
	return {
		schema: EmbeddedModelSchemaToJSON(value.schema),
		iterable: (value.iterable as any[]).map(
			SeededDiscoverableRelatedTagToJSON,
		),
		application: value.application,
	};
}
