/* tslint:disable */
/* eslint-disable */
/**
 * Pieces Isomorphic OpenAPI
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from "../runtime.ts";
import type { EmbeddedModelSchema } from "./EmbeddedModelSchema.tsx";
import {
	EmbeddedModelSchemaFromJSON,
	EmbeddedModelSchemaToJSON,
} from "./EmbeddedModelSchema.tsx";
import type { SeededConnectorAsset } from "./SeededConnectorAsset.tsx";
import {
	SeededConnectorAssetFromJSON,
	SeededConnectorAssetToJSON,
} from "./SeededConnectorAsset.tsx";

/**
 * A encompasing creation object that can be utilized to create either an asset or a format.
 * @export
 * @interface SeededConnectorCreation
 */
export interface SeededConnectorCreation {
	/**
	 *
	 * @type {EmbeddedModelSchema}
	 * @memberof SeededConnectorCreation
	 */
	schema?: EmbeddedModelSchema;
	/**
	 *
	 * @type {SeededConnectorAsset}
	 * @memberof SeededConnectorCreation
	 */
	asset?: SeededConnectorAsset;
}

/**
 * Check if a given object implements the SeededConnectorCreation interface.
 */
export function instanceOfSeededConnectorCreation(_value: object): boolean {
	const isInstance = true;

	return isInstance;
}

export function SeededConnectorCreationFromJSON(
	json: any,
): SeededConnectorCreation {
	return SeededConnectorCreationFromJSONTyped(json, false);
}

export function SeededConnectorCreationFromJSONTyped(
	json: any,
	_ignoreDiscriminator: boolean,
): SeededConnectorCreation {
	if (json === undefined || json === null) {
		return json;
	}
	return {
		schema: exists(json, "schema")
			? EmbeddedModelSchemaFromJSON(json["schema"])
			: undefined,
		asset: exists(json, "asset")
			? SeededConnectorAssetFromJSON(json["asset"])
			: undefined,
	};
}

export function SeededConnectorCreationToJSON(
	value?: SeededConnectorCreation | null,
): any {
	if (value === undefined) {
		return undefined;
	}
	if (value === null) {
		return null;
	}
	return {
		schema: EmbeddedModelSchemaToJSON(value.schema),
		asset: SeededConnectorAssetToJSON(value.asset),
	};
}
