/* tslint:disable */
/* eslint-disable */
/**
 * Pieces Isomorphic OpenAPI
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from "../runtime.ts";
import type { EmbeddedModelSchema } from "./EmbeddedModelSchema.tsx";
import {
	EmbeddedModelSchemaFromJSON,
	EmbeddedModelSchemaToJSON,
} from "./EmbeddedModelSchema.tsx";
import type { SeededTrackedApplication } from "./SeededTrackedApplication.tsx";
import {
	SeededTrackedApplicationFromJSON,
	SeededTrackedApplicationToJSON,
} from "./SeededTrackedApplication.tsx";

/**
 * A model that is passed to the context API at bootup
 * @export
 * @interface SeededConnectorConnection
 */
export interface SeededConnectorConnection {
	/**
	 *
	 * @type {EmbeddedModelSchema}
	 * @memberof SeededConnectorConnection
	 */
	schema?: EmbeddedModelSchema;
	/**
	 *
	 * @type {SeededTrackedApplication}
	 * @memberof SeededConnectorConnection
	 */
	application: SeededTrackedApplication;
}

/**
 * Check if a given object implements the SeededConnectorConnection interface.
 */
export function instanceOfSeededConnectorConnection(value: object): boolean {
	let isInstance = true;
	isInstance = isInstance && "application" in value;

	return isInstance;
}

export function SeededConnectorConnectionFromJSON(
	json: any,
): SeededConnectorConnection {
	return SeededConnectorConnectionFromJSONTyped(json, false);
}

export function SeededConnectorConnectionFromJSONTyped(
	json: any,
	_ignoreDiscriminator: boolean,
): SeededConnectorConnection {
	if (json === undefined || json === null) {
		return json;
	}
	return {
		schema: exists(json, "schema")
			? EmbeddedModelSchemaFromJSON(json["schema"])
			: undefined,
		application: SeededTrackedApplicationFromJSON(json["application"]),
	};
}

export function SeededConnectorConnectionToJSON(
	value?: SeededConnectorConnection | null,
): any {
	if (value === undefined) {
		return undefined;
	}
	if (value === null) {
		return null;
	}
	return {
		schema: EmbeddedModelSchemaToJSON(value.schema),
		application: SeededTrackedApplicationToJSON(value.application),
	};
}
