/* tslint:disable */
/* eslint-disable */
/**
 * Pieces Isomorphic OpenAPI
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from "../runtime.ts";
import type { EmbeddedModelSchema } from "./EmbeddedModelSchema.tsx";
import {
	EmbeddedModelSchemaFromJSON,
	EmbeddedModelSchemaToJSON,
} from "./EmbeddedModelSchema.tsx";
import type { Score } from "./Score.tsx";
import { ScoreFromJSON, ScoreToJSON } from "./Score.tsx";
import type { Share } from "./Share.tsx";
import { ShareFromJSON, ShareToJSON } from "./Share.tsx";

/**
 * this is just an iterable of our individual share models.
 * @export
 * @interface Shares
 */
export interface Shares {
	/**
	 *
	 * @type {EmbeddedModelSchema}
	 * @memberof Shares
	 */
	schema?: EmbeddedModelSchema;
	/**
	 * this is just an iterable of our individual share models.
	 * @type {Array<Share>}
	 * @memberof Shares
	 */
	iterable: Share[];
	/**
	 *
	 * @type {Score}
	 * @memberof Shares
	 */
	score?: Score;
}

/**
 * Check if a given object implements the Shares interface.
 */
export function instanceOfShares(value: object): boolean {
	let isInstance = true;
	isInstance = isInstance && "iterable" in value;

	return isInstance;
}

export function SharesFromJSON(json: any): Shares {
	return SharesFromJSONTyped(json, false);
}

export function SharesFromJSONTyped(
	json: any,
	_ignoreDiscriminator: boolean,
): Shares {
	if (json === undefined || json === null) {
		return json;
	}
	return {
		schema: exists(json, "schema")
			? EmbeddedModelSchemaFromJSON(json["schema"])
			: undefined,
		iterable: (json["iterable"] as any[]).map(ShareFromJSON),
		score: exists(json, "score") ? ScoreFromJSON(json["score"]) : undefined,
	};
}

export function SharesToJSON(value?: Shares | null): any {
	if (value === undefined) {
		return undefined;
	}
	if (value === null) {
		return null;
	}
	return {
		schema: EmbeddedModelSchemaToJSON(value.schema),
		iterable: (value.iterable as any[]).map(ShareToJSON),
		score: ScoreToJSON(value.score),
	};
}
