/* tslint:disable */
/* eslint-disable */
/**
 * Pieces Isomorphic OpenAPI
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from "../runtime.ts";
import {
	EmbeddedModelSchemaFromJSON,
	EmbeddedModelSchemaToJSON,
	type EmbeddedModelSchema,
} from "./EmbeddedModelSchema.tsx";
import {
	TLPCodeSnippetTagifyCodeFromJSON,
	TLPCodeSnippetTagifyCodeToJSON,
	type TLPCodeSnippetTagifyCode,
} from "./TLPCodeSnippetTagifyCode.tsx";

/**
 *
 * @export
 * @interface TLPCodeFragmentTagify
 */
export interface TLPCodeFragmentTagify {
	/**
	 *
	 * @type {EmbeddedModelSchema}
	 * @memberof TLPCodeFragmentTagify
	 */
	schema?: EmbeddedModelSchema;
	/**
	 *
	 * @type {TLPCodeSnippetTagifyCode}
	 * @memberof TLPCodeFragmentTagify
	 */
	code?: TLPCodeSnippetTagifyCode;
}

/**
 * Check if a given object implements the TLPCodeFragmentTagify interface.
 */
export function instanceOfTLPCodeFragmentTagify(_value: object): boolean {
	const isInstance = true;

	return isInstance;
}

export function TLPCodeFragmentTagifyFromJSON(
	json: any,
): TLPCodeFragmentTagify {
	return TLPCodeFragmentTagifyFromJSONTyped(json, false);
}

export function TLPCodeFragmentTagifyFromJSONTyped(
	json: any,
	_ignoreDiscriminator: boolean,
): TLPCodeFragmentTagify {
	if (json === undefined || json === null) {
		return json;
	}
	return {
		schema: exists(json, "schema")
			? EmbeddedModelSchemaFromJSON(json["schema"])
			: undefined,
		code: exists(json, "code")
			? TLPCodeSnippetTagifyCodeFromJSON(json["code"])
			: undefined,
	};
}

export function TLPCodeFragmentTagifyToJSON(
	value?: TLPCodeFragmentTagify | null,
): any {
	if (value === undefined) {
		return undefined;
	}
	if (value === null) {
		return null;
	}
	return {
		schema: EmbeddedModelSchemaToJSON(value.schema),
		code: TLPCodeSnippetTagifyCodeToJSON(value.code),
	};
}
