/* tslint:disable */
/* eslint-disable */
/**
 * Pieces Isomorphic OpenAPI
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from "../runtime.ts";
import type { EmbeddedModelSchema } from "./EmbeddedModelSchema.tsx";
import {
	EmbeddedModelSchemaFromJSON,
	EmbeddedModelSchemaToJSON,
} from "./EmbeddedModelSchema.tsx";
import type { TLPCodeFragmentDescriptiveStatistics } from "./TLPCodeFragmentDescriptiveStatistics.tsx";
import {
	TLPCodeFragmentDescriptiveStatisticsFromJSON,
	TLPCodeFragmentDescriptiveStatisticsToJSON,
} from "./TLPCodeFragmentDescriptiveStatistics.tsx";

/**
 *
 * @export
 * @interface TLPCodeFragmentStatistics
 */
export interface TLPCodeFragmentStatistics {
	/**
	 *
	 * @type {EmbeddedModelSchema}
	 * @memberof TLPCodeFragmentStatistics
	 */
	schema?: EmbeddedModelSchema;
	/**
	 *
	 * @type {TLPCodeFragmentDescriptiveStatistics}
	 * @memberof TLPCodeFragmentStatistics
	 */
	descriptive?: TLPCodeFragmentDescriptiveStatistics;
}

/**
 * Check if a given object implements the TLPCodeFragmentStatistics interface.
 */
export function instanceOfTLPCodeFragmentStatistics(_value: object): boolean {
	const isInstance = true;

	return isInstance;
}

export function TLPCodeFragmentStatisticsFromJSON(
	json: any,
): TLPCodeFragmentStatistics {
	return TLPCodeFragmentStatisticsFromJSONTyped(json, false);
}

export function TLPCodeFragmentStatisticsFromJSONTyped(
	json: any,
	_ignoreDiscriminator: boolean,
): TLPCodeFragmentStatistics {
	if (json === undefined || json === null) {
		return json;
	}
	return {
		schema: exists(json, "schema")
			? EmbeddedModelSchemaFromJSON(json["schema"])
			: undefined,
		descriptive: exists(json, "descriptive")
			? TLPCodeFragmentDescriptiveStatisticsFromJSON(json["descriptive"])
			: undefined,
	};
}

export function TLPCodeFragmentStatisticsToJSON(
	value?: TLPCodeFragmentStatistics | null,
): any {
	if (value === undefined) {
		return undefined;
	}
	if (value === null) {
		return null;
	}
	return {
		schema: EmbeddedModelSchemaToJSON(value.schema),
		descriptive: TLPCodeFragmentDescriptiveStatisticsToJSON(
			value.descriptive,
		),
	};
}
