/* tslint:disable */
/* eslint-disable */
/**
 * Pieces Isomorphic OpenAPI
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from "../runtime.ts";
import type { EmbeddedModelSchema } from "./EmbeddedModelSchema.tsx";
import {
	EmbeddedModelSchemaFromJSON,
	EmbeddedModelSchemaToJSON,
} from "./EmbeddedModelSchema.tsx";
import type { TrackedAssetEventCreationMetadataClipboard } from "./TrackedAssetEventCreationMetadataClipboard.tsx";
import {
	TrackedAssetEventCreationMetadataClipboardFromJSON,
	TrackedAssetEventCreationMetadataClipboardToJSON,
} from "./TrackedAssetEventCreationMetadataClipboard.tsx";
import type { TrackedAssetEventCreationMetadataFile } from "./TrackedAssetEventCreationMetadataFile.tsx";
import {
	TrackedAssetEventCreationMetadataFileFromJSON,
	TrackedAssetEventCreationMetadataFileToJSON,
} from "./TrackedAssetEventCreationMetadataFile.tsx";

/**
 * Metadata attached to a creation event on an Asset
 * @export
 * @interface TrackedAssetEventCreationMetadata
 */
export interface TrackedAssetEventCreationMetadata {
	/**
	 *
	 * @type {EmbeddedModelSchema}
	 * @memberof TrackedAssetEventCreationMetadata
	 */
	schema?: EmbeddedModelSchema;
	/**
	 *
	 * @type {TrackedAssetEventCreationMetadataClipboard}
	 * @memberof TrackedAssetEventCreationMetadata
	 */
	clipboard?: TrackedAssetEventCreationMetadataClipboard;
	/**
	 *
	 * @type {TrackedAssetEventCreationMetadataFile}
	 * @memberof TrackedAssetEventCreationMetadata
	 */
	file?: TrackedAssetEventCreationMetadataFile;
}

/**
 * Check if a given object implements the TrackedAssetEventCreationMetadata interface.
 */
export function instanceOfTrackedAssetEventCreationMetadata(
	_value: object,
): boolean {
	const isInstance = true;

	return isInstance;
}

export function TrackedAssetEventCreationMetadataFromJSON(
	json: any,
): TrackedAssetEventCreationMetadata {
	return TrackedAssetEventCreationMetadataFromJSONTyped(json, false);
}

export function TrackedAssetEventCreationMetadataFromJSONTyped(
	json: any,
	_ignoreDiscriminator: boolean,
): TrackedAssetEventCreationMetadata {
	if (json === undefined || json === null) {
		return json;
	}
	return {
		schema: exists(json, "schema")
			? EmbeddedModelSchemaFromJSON(json["schema"])
			: undefined,
		clipboard: exists(json, "clipboard")
			? TrackedAssetEventCreationMetadataClipboardFromJSON(
					json["clipboard"],
				)
			: undefined,
		file: exists(json, "file")
			? TrackedAssetEventCreationMetadataFileFromJSON(json["file"])
			: undefined,
	};
}

export function TrackedAssetEventCreationMetadataToJSON(
	value?: TrackedAssetEventCreationMetadata | null,
): any {
	if (value === undefined) {
		return undefined;
	}
	if (value === null) {
		return null;
	}
	return {
		schema: EmbeddedModelSchemaToJSON(value.schema),
		clipboard: TrackedAssetEventCreationMetadataClipboardToJSON(
			value.clipboard,
		),
		file: TrackedAssetEventCreationMetadataFileToJSON(value.file),
	};
}
