/* tslint:disable */
/* eslint-disable */
/**
 * Pieces Isomorphic OpenAPI
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from "../runtime.ts";
import type { EmbeddedModelSchema } from "./EmbeddedModelSchema.tsx";
import {
	EmbeddedModelSchemaFromJSON,
	EmbeddedModelSchemaToJSON,
} from "./EmbeddedModelSchema.tsx";
import type { TrackedFormat } from "./TrackedFormat.tsx";
import {
	TrackedFormatFromJSON,
	TrackedFormatToJSON,
} from "./TrackedFormat.tsx";
import type { TrackedFormatEventIdentifierDescriptionPairs } from "./TrackedFormatEventIdentifierDescriptionPairs.tsx";
import {
	TrackedFormatEventIdentifierDescriptionPairsFromJSON,
	TrackedFormatEventIdentifierDescriptionPairsToJSON,
} from "./TrackedFormatEventIdentifierDescriptionPairs.tsx";
import type { TrackedFormatEventMetadata } from "./TrackedFormatEventMetadata.tsx";
import {
	TrackedFormatEventMetadataFromJSON,
	TrackedFormatEventMetadataToJSON,
} from "./TrackedFormatEventMetadata.tsx";

/**
 * This is a model that represents a generic event that we may want to track in relation to a format, for example beamed, copied, downloaded, and view. ** Note: This is the model that will get returned by our api, and is. Representative of a full TrackedFormat event. **
 * @export
 * @interface TrackedFormatEvent
 */
export interface TrackedFormatEvent {
	/**
	 *
	 * @type {EmbeddedModelSchema}
	 * @memberof TrackedFormatEvent
	 */
	schema?: EmbeddedModelSchema;
	/**
	 *
	 * @type {TrackedFormat}
	 * @memberof TrackedFormatEvent
	 */
	format: TrackedFormat;
	/**
	 *
	 * @type {TrackedFormatEventIdentifierDescriptionPairs}
	 * @memberof TrackedFormatEvent
	 */
	identifierDescriptionPair: TrackedFormatEventIdentifierDescriptionPairs;
	/**
	 *
	 * @type {TrackedFormatEventMetadata}
	 * @memberof TrackedFormatEvent
	 */
	metadata?: TrackedFormatEventMetadata;
}

/**
 * Check if a given object implements the TrackedFormatEvent interface.
 */
export function instanceOfTrackedFormatEvent(value: object): boolean {
	let isInstance = true;
	isInstance = isInstance && "format" in value;
	isInstance = isInstance && "identifierDescriptionPair" in value;

	return isInstance;
}

export function TrackedFormatEventFromJSON(json: any): TrackedFormatEvent {
	return TrackedFormatEventFromJSONTyped(json, false);
}

export function TrackedFormatEventFromJSONTyped(
	json: any,
	_ignoreDiscriminator: boolean,
): TrackedFormatEvent {
	if (json === undefined || json === null) {
		return json;
	}
	return {
		schema: exists(json, "schema")
			? EmbeddedModelSchemaFromJSON(json["schema"])
			: undefined,
		format: TrackedFormatFromJSON(json[" format"]),
		identifierDescriptionPair:
			TrackedFormatEventIdentifierDescriptionPairsFromJSON(
				json["identifier_description_pair"],
			),
		metadata: exists(json, "metadata")
			? TrackedFormatEventMetadataFromJSON(json["metadata"])
			: undefined,
	};
}

export function TrackedFormatEventToJSON(
	value?: TrackedFormatEvent | null,
): any {
	if (value === undefined) {
		return undefined;
	}
	if (value === null) {
		return null;
	}
	return {
		schema: EmbeddedModelSchemaToJSON(value.schema),
		" format": TrackedFormatToJSON(value.format),
		identifier_description_pair:
			TrackedFormatEventIdentifierDescriptionPairsToJSON(
				value.identifierDescriptionPair,
			),
		metadata: TrackedFormatEventMetadataToJSON(value.metadata),
	};
}
