/* tslint:disable */
/* eslint-disable */
/**
 * Pieces Isomorphic OpenAPI
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from "../runtime.ts";
import type { EmbeddedModelSchema } from "./EmbeddedModelSchema.tsx";
import {
	EmbeddedModelSchemaFromJSON,
	EmbeddedModelSchemaToJSON,
} from "./EmbeddedModelSchema.tsx";
import type { Score } from "./Score.tsx";
import { ScoreFromJSON, ScoreToJSON } from "./Score.tsx";
import type { Website } from "./Website.tsx";
import { WebsiteFromJSON, WebsiteToJSON } from "./Website.tsx";

/**
 * This is a specific model for related websites to an asset.
 * @export
 * @interface Websites
 */
export interface Websites {
	/**
	 *
	 * @type {EmbeddedModelSchema}
	 * @memberof Websites
	 */
	schema?: EmbeddedModelSchema;
	/**
	 *
	 * @type {Array<Website>}
	 * @memberof Websites
	 */
	iterable: Website[];
	/**
	 * This is a Map<String, int> where the the key is an website id.
	 * @type {{ [key: string]: number; }}
	 * @memberof Websites
	 */
	indices?: { [key: string]: number };
	/**
	 *
	 * @type {Score}
	 * @memberof Websites
	 */
	score?: Score;
}

/**
 * Check if a given object implements the Websites interface.
 */
export function instanceOfWebsites(value: object): boolean {
	let isInstance = true;
	isInstance = isInstance && "iterable" in value;

	return isInstance;
}

export function WebsitesFromJSON(json: any): Websites {
	return WebsitesFromJSONTyped(json, false);
}

export function WebsitesFromJSONTyped(
	json: any,
	_ignoreDiscriminator: boolean,
): Websites {
	if (json === undefined || json === null) {
		return json;
	}
	return {
		schema: exists(json, "schema")
			? EmbeddedModelSchemaFromJSON(json["schema"])
			: undefined,
		iterable: (json["iterable"] as any[]).map(WebsiteFromJSON),
		indices: exists(json, "indices") ? json["indices"] : undefined,
		score: exists(json, "score") ? ScoreFromJSON(json["score"]) : undefined,
	};
}

export function WebsitesToJSON(value?: Websites | null): any {
	if (value === undefined) {
		return undefined;
	}
	if (value === null) {
		return null;
	}
	return {
		schema: EmbeddedModelSchemaToJSON(value.schema),
		iterable: (value.iterable as any[]).map(WebsiteToJSON),
		indices: value.indices,
		score: ScoreToJSON(value.score),
	};
}
