/* tslint:disable */
/* eslint-disable */
/**
 * Pieces Isomorphic OpenAPI
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from "../runtime.ts";
import {
	EmbeddedModelSchemaFromJSON,
	EmbeddedModelSchemaToJSON,
	type EmbeddedModelSchema,
} from "./EmbeddedModelSchema.tsx";
import {
	WorkstreamPatternEngineVisionCalibrationFromJSON,
	WorkstreamPatternEngineVisionCalibrationToJSON,
	type WorkstreamPatternEngineVisionCalibration,
} from "./WorkstreamPatternEngineVisionCalibration.tsx";

/**
 * TODO: description
 * This the plural of a single copilot Capture.
 *
 * This will return all the the given copilot captures
 * @export
 * @interface WorkstreamPatternEngineVisionCalibrations
 */
export interface WorkstreamPatternEngineVisionCalibrations {
	/**
	 *
	 * @type {EmbeddedModelSchema}
	 * @memberof WorkstreamPatternEngineVisionCalibrations
	 */
	schema?: EmbeddedModelSchema;
	/**
	 *
	 * @type {Array<WorkstreamPatternEngineVisionCalibration>}
	 * @memberof WorkstreamPatternEngineVisionCalibrations
	 */
	iterable: WorkstreamPatternEngineVisionCalibration[];
}

/**
 * Check if a given object implements the WorkstreamPatternEngineVisionCalibrations interface.
 */
export function instanceOfWorkstreamPatternEngineVisionCalibrations(
	value: object,
): boolean {
	let isInstance = true;
	isInstance = isInstance && "iterable" in value;

	return isInstance;
}

export function WorkstreamPatternEngineVisionCalibrationsFromJSON(
	json: any,
): WorkstreamPatternEngineVisionCalibrations {
	return WorkstreamPatternEngineVisionCalibrationsFromJSONTyped(json, false);
}

export function WorkstreamPatternEngineVisionCalibrationsFromJSONTyped(
	json: any,
	_ignoreDiscriminator: boolean,
): WorkstreamPatternEngineVisionCalibrations {
	if (json === undefined || json === null) {
		return json;
	}
	return {
		schema: exists(json, "schema")
			? EmbeddedModelSchemaFromJSON(json["schema"])
			: undefined,
		iterable: (json["iterable"] as any[]).map(
			WorkstreamPatternEngineVisionCalibrationFromJSON,
		),
	};
}

export function WorkstreamPatternEngineVisionCalibrationsToJSON(
	value?: WorkstreamPatternEngineVisionCalibrations | null,
): any {
	if (value === undefined) {
		return undefined;
	}
	if (value === null) {
		return null;
	}
	return {
		schema: EmbeddedModelSchemaToJSON(value.schema),
		iterable: (value.iterable as any[]).map(
			WorkstreamPatternEngineVisionCalibrationToJSON,
		),
	};
}
