/* tslint:disable */
/* eslint-disable */
/**
 * Pieces Isomorphic OpenAPI
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from "../runtime.ts";
import type { EmbeddedModelSchema } from "./EmbeddedModelSchema.tsx";
import {
	EmbeddedModelSchemaFromJSON,
	EmbeddedModelSchemaToJSON,
} from "./EmbeddedModelSchema.tsx";
import type { WorkstreamPatternEngineVisionEventsMetadata } from "./WorkstreamPatternEngineVisionEventsMetadata.tsx";
import {
	WorkstreamPatternEngineVisionEventsMetadataFromJSON,
	WorkstreamPatternEngineVisionEventsMetadataToJSON,
} from "./WorkstreamPatternEngineVisionEventsMetadata.tsx";

/**
 * This will return all the WPE vision specific metadata
 * @export
 * @interface WorkstreamPatternEngineVisionMetadata
 */
export interface WorkstreamPatternEngineVisionMetadata {
	/**
	 *
	 * @type {EmbeddedModelSchema}
	 * @memberof WorkstreamPatternEngineVisionMetadata
	 */
	schema?: EmbeddedModelSchema;
	/**
	 *
	 * @type {WorkstreamPatternEngineVisionEventsMetadata}
	 * @memberof WorkstreamPatternEngineVisionMetadata
	 */
	events?: WorkstreamPatternEngineVisionEventsMetadata;
}

/**
 * Check if a given object implements the WorkstreamPatternEngineVisionMetadata interface.
 */
export function instanceOfWorkstreamPatternEngineVisionMetadata(
	_value: object,
): boolean {
	const isInstance = true;

	return isInstance;
}

export function WorkstreamPatternEngineVisionMetadataFromJSON(
	json: any,
): WorkstreamPatternEngineVisionMetadata {
	return WorkstreamPatternEngineVisionMetadataFromJSONTyped(json, false);
}

export function WorkstreamPatternEngineVisionMetadataFromJSONTyped(
	json: any,
	_ignoreDiscriminator: boolean,
): WorkstreamPatternEngineVisionMetadata {
	if (json === undefined || json === null) {
		return json;
	}
	return {
		schema: exists(json, "schema")
			? EmbeddedModelSchemaFromJSON(json["schema"])
			: undefined,
		events: exists(json, "events")
			? WorkstreamPatternEngineVisionEventsMetadataFromJSON(
					json["events"],
				)
			: undefined,
	};
}

export function WorkstreamPatternEngineVisionMetadataToJSON(
	value?: WorkstreamPatternEngineVisionMetadata | null,
): any {
	if (value === undefined) {
		return undefined;
	}
	if (value === null) {
		return null;
	}
	return {
		schema: EmbeddedModelSchemaToJSON(value.schema),
		events: WorkstreamPatternEngineVisionEventsMetadataToJSON(value.events),
	};
}
