/* tslint:disable */
/* eslint-disable */
/**
 * Pieces Isomorphic OpenAPI
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from "../runtime.ts";
import {
	EmbeddedModelSchemaFromJSON,
	EmbeddedModelSchemaToJSON,
	type EmbeddedModelSchema,
} from "./EmbeddedModelSchema.tsx";
import {
	WorkstreamPatternEngineSourcesFromJSON,
	WorkstreamPatternEngineSourcesToJSON,
	type WorkstreamPatternEngineSources,
} from "./WorkstreamPatternEngineSources.tsx";

/**
 * This is a search realted to the workstream pattern engine data,
 * for instance in a WPE/vision/search we will want to be able to search via a WorkstreamPatternEngineSource.
 * @export
 * @interface WorkstreamSearchOptions
 */
export interface WorkstreamSearchOptions {
	/**
	 *
	 * @type {EmbeddedModelSchema}
	 * @memberof WorkstreamSearchOptions
	 */
	schema?: EmbeddedModelSchema;
	/**
	 *
	 * @type {WorkstreamPatternEngineSources}
	 * @memberof WorkstreamSearchOptions
	 */
	sources?: WorkstreamPatternEngineSources;
}

/**
 * Check if a given object implements the WorkstreamSearchOptions interface.
 */
export function instanceOfWorkstreamSearchOptions(_value: object): boolean {
	const isInstance = true;

	return isInstance;
}

export function WorkstreamSearchOptionsFromJSON(
	json: any,
): WorkstreamSearchOptions {
	return WorkstreamSearchOptionsFromJSONTyped(json, false);
}

export function WorkstreamSearchOptionsFromJSONTyped(
	json: any,
	_ignoreDiscriminator: boolean,
): WorkstreamSearchOptions {
	if (json === undefined || json === null) {
		return json;
	}
	return {
		schema: exists(json, "schema")
			? EmbeddedModelSchemaFromJSON(json["schema"])
			: undefined,
		sources: exists(json, "sources")
			? WorkstreamPatternEngineSourcesFromJSON(json["sources"])
			: undefined,
	};
}

export function WorkstreamSearchOptionsToJSON(
	value?: WorkstreamSearchOptions | null,
): any {
	if (value === undefined) {
		return undefined;
	}
	if (value === null) {
		return null;
	}
	return {
		schema: EmbeddedModelSchemaToJSON(value.schema),
		sources: WorkstreamPatternEngineSourcesToJSON(value.sources),
	};
}
