/* tslint:disable */
/* eslint-disable */
/**
 * Pieces Isomorphic OpenAPI
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from "../runtime.ts";
import type { AnonymousTemporalRange } from "./AnonymousTemporalRange.tsx";
import {
	AnonymousTemporalRangeFromJSON,
	AnonymousTemporalRangeToJSON,
} from "./AnonymousTemporalRange.tsx";
import type { EmbeddedModelSchema } from "./EmbeddedModelSchema.tsx";
import {
	EmbeddedModelSchemaFromJSON,
	EmbeddedModelSchemaToJSON,
} from "./EmbeddedModelSchema.tsx";

/**
 * activation: can be active for forever w/ continous true, or it can be activated for the next couple hours
 *
 * deactivation: here can be deactivated for forever w/ continuous true, or it can be deactivated for the next couple hours
 *
 * Note: one or the other will be set and both are nullable.
 * @export
 * @interface WorkstreamPatternEngineVisionStatus
 */
export interface WorkstreamPatternEngineVisionStatus {
	/**
	 *
	 * @type {EmbeddedModelSchema}
	 * @memberof WorkstreamPatternEngineVisionStatus
	 */
	schema?: EmbeddedModelSchema;
	/**
	 *
	 * @type {AnonymousTemporalRange}
	 * @memberof WorkstreamPatternEngineVisionStatus
	 */
	activation?: AnonymousTemporalRange;
	/**
	 *
	 * @type {AnonymousTemporalRange}
	 * @memberof WorkstreamPatternEngineVisionStatus
	 */
	deactivation?: AnonymousTemporalRange;
}

/**
 * Check if a given object implements the WorkstreamPatternEngineVisionStatus interface.
 */
export function instanceOfWorkstreamPatternEngineVisionStatus(
	_value: object,
): boolean {
	const isInstance = true;

	return isInstance;
}

export function WorkstreamPatternEngineVisionStatusFromJSON(
	json: any,
): WorkstreamPatternEngineVisionStatus {
	return WorkstreamPatternEngineVisionStatusFromJSONTyped(json, false);
}

export function WorkstreamPatternEngineVisionStatusFromJSONTyped(
	json: any,
	_ignoreDiscriminator: boolean,
): WorkstreamPatternEngineVisionStatus {
	if (json === undefined || json === null) {
		return json;
	}
	return {
		schema: exists(json, "schema")
			? EmbeddedModelSchemaFromJSON(json["schema"])
			: undefined,
		activation: exists(json, "activation")
			? AnonymousTemporalRangeFromJSON(json["activation"])
			: undefined,
		deactivation: exists(json, "deactivation")
			? AnonymousTemporalRangeFromJSON(json["deactivation"])
			: undefined,
	};
}

export function WorkstreamPatternEngineVisionStatusToJSON(
	value?: WorkstreamPatternEngineVisionStatus | null,
): any {
	if (value === undefined) {
		return undefined;
	}
	if (value === null) {
		return null;
	}
	return {
		schema: EmbeddedModelSchemaToJSON(value.schema),
		activation: AnonymousTemporalRangeToJSON(value.activation),
		deactivation: AnonymousTemporalRangeToJSON(value.deactivation),
	};
}
