/* tslint:disable */
/* eslint-disable */
/**
 * Pieces Isomorphic OpenAPI
 * Endpoints for Assets, Formats, Users, Asset, Format, User.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tsavo@pieces.app
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from "../runtime.ts";
import {
	EmbeddedModelSchemaFromJSON,
	EmbeddedModelSchemaToJSON,
	type EmbeddedModelSchema,
} from "./EmbeddedModelSchema.tsx";
import {
	WorkstreamPatternEngineSourceFromJSON,
	WorkstreamPatternEngineSourceToJSON,
	type WorkstreamPatternEngineSource,
} from "./WorkstreamPatternEngineSource.tsx";

/**
 * This is a plural version of the WPE qdrant applications
 * @export
 * @interface WorkstreamPatternEngineSources
 */
export interface WorkstreamPatternEngineSources {
	/**
	 *
	 * @type {EmbeddedModelSchema}
	 * @memberof WorkstreamPatternEngineSources
	 */
	schema?: EmbeddedModelSchema;
	/**
	 *
	 * @type {Array<WorkstreamPatternEngineSource>}
	 * @memberof WorkstreamPatternEngineSources
	 */
	iterable: WorkstreamPatternEngineSource[];
}

/**
 * Check if a given object implements the WorkstreamPatternEngineSources interface.
 */
export function instanceOfWorkstreamPatternEngineSources(
	value: object,
): boolean {
	let isInstance = true;
	isInstance = isInstance && "iterable" in value;

	return isInstance;
}

export function WorkstreamPatternEngineSourcesFromJSON(
	json: any,
): WorkstreamPatternEngineSources {
	return WorkstreamPatternEngineSourcesFromJSONTyped(json, false);
}

export function WorkstreamPatternEngineSourcesFromJSONTyped(
	json: any,
	_ignoreDiscriminator: boolean,
): WorkstreamPatternEngineSources {
	if (json === undefined || json === null) {
		return json;
	}
	return {
		schema: exists(json, "schema")
			? EmbeddedModelSchemaFromJSON(json["schema"])
			: undefined,
		iterable: (json["iterable"] as any[]).map(
			WorkstreamPatternEngineSourceFromJSON,
		),
	};
}

export function WorkstreamPatternEngineSourcesToJSON(
	value?: WorkstreamPatternEngineSources | null,
): any {
	if (value === undefined) {
		return undefined;
	}
	if (value === null) {
		return null;
	}
	return {
		schema: EmbeddedModelSchemaToJSON(value.schema),
		iterable: (value.iterable as any[]).map(
			WorkstreamPatternEngineSourceToJSON,
		),
	};
}
